execution:
  parralel_jobs: 1
connection:
  jbnas:
    host: jbnas
    remote_user: jb
    dest_folder: /data
pipelines:
  "compress encrypt":
    type: backup pipeline
    connection: ssh
    local:
      - operation: tar
      - operation: compress
        algorithm: gzip
        level: 6
      - operation: gpg encrypt
        key: B4B3E302D6531426
      - operation: gpg sign
        key: 3CBF323610829410
    remote:
      - operation: save backup
        dest_file: "{dest_folder}/{dest_filename}{date}{extensions}"
      - operation: sync
  "compress encrypt push":
    type: backup pipeline
    connection: ssh
    local:
      - operation: tar
      - operation: compress
        algorithm: gzip
        level: 6
      - operation: gpg encrypt
        key: B4B3E302D6531426
      - operation: gpg sign
        key: 3CBF323610829410
    remote:
      - operation: save backup
        dest_file: "{dest_folder}/{dest_filename}{date}{extensions}"
      - operation: sync
      - operation: push to cloud
        sync: false
        target: gs://bucket/backups
        type: gcloud

folders:
  - folders: /tmp/foo /tmp/bar
    file_name: foobar
    pipeline: compress encrypt push
    connection: jbnas
